# Generated by Django 4.2.4 on 2023-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contractAddress', models.CharField(max_length=60)),
                ('jettonWalletAddress', models.CharField(max_length=60)),
                ('stonfiPoolAddress', models.CharField(max_length=60)),
                ('jettonType', models.CharField(choices=[('LP', 'LP'), ('Jetton', 'Jetton')], max_length=6)),
                ('jettonTvl', models.BigIntegerField(default=0, null=True)),
                ('tonTvl', models.FloatField(default=0)),
                ('usdTvl', models.FloatField(default=0)),
                ('testnet', models.BooleanField(default=False)),
                ('category', models.SmallIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Staker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stakerAddress', models.CharField(max_length=60)),
                ('poolName', models.CharField(max_length=20)),
                ('stakedJettons', models.BigIntegerField(default=0)),
                ('tonEquivalent', models.FloatField(default=0)),
                ('stakerNftItems', models.JSONField(default=dict)),
                ('testnet', models.BooleanField(default=False)),
            ],
        ),
    ]
